/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Browser {
  Chrome = 0,
  Firefox = 1
}
export interface RetcherOptions {
  browser?: Browser
  ignoreTlsErrors?: boolean
  vanillaFallback?: boolean
  proxyUrl?: string
}
export declare class NapiResponseWrapper {
  status: number
  statusText: string
  headers: Record<string, string>
  ok: boolean
  bytes(): Buffer
  text(): string
  json(): any
}
export declare class NodeRetcherWrapper {
  constructor(options: RetcherOptions)
  fetch(url: string): Promise<NapiResponseWrapper>
}
